### ISSUE TITLE
Numpy - error when updating to newest version of PiConsole 

### ISSUE THREAD

**Issue by DMEbner** [peted-davis/WeatherFlow_PiConsole#131]
Hello friends!

I have been trying to the most current version of Pi Console but I keep getting error that it can't install the numpy module. 
![IMG_7597](https://github.com/peted-davis/WeatherFlow_PiConsole/assets/109828266/d77cd68b-7442-4df7-a5c9-9d0e70e44b51)

Numpy is loaded on my Rasp. Pi. Can anyone give me some direction? 

Cheers!

**Comment by peted-davis** [comment]
Sorry you have run into trouble. It looks like this happens if Numpy is already installed on the Pi. To fix the issue, please open a terminal and run the following commands:

`source ~/wfpiconsole/venv/bin/activate`
`python3 -m pip install --no-cache-dir numpy==1.26.0`
`deactivate`

Once those three commands have run, try to update the console again with `wfpiconsole update`

**Comment by DMEbner** [comment]
Thank you for the help. It says there is no such file or directory. Should
I just reinstall Pi Console on my Pi?

**Comment by peted-davis** [comment]
Yes, just try reinstalling. I have just pushed an update that should fix the issue you are seeing

**Comment by peted-davis** [comment]
This error should now be fixed in v23.11.1
