### ISSUE TITLE
Last strike in minutes 1 digit instead of 2.

### ISSUE THREAD

**Issue by pjmpessers** [peted-davis/WeatherFlow_PiConsole#35]
Hello.

I love the wfpiconsole. I use it every day. It was for the first time i got a strike yesterday. It is shown on the wfpiconsole what is great. But when last strike is shown the minute under ten is shown with one digit instead of two. For example i get: "last strike 16:2 instead of 16:02. Can this be corrected? 10 or above is shown correct. Like:"16:15.

Thanks again.

**Comment by peted-davis** [comment]
Sure - I will have a look at this. It sounds like a small glitch. Are you using the Official 7 inch Raspberry Pi touchscreen, or something different?

If possible, can you share a photo or screenshot showing the issue?

**Comment by pjmpessers** [comment]
In the bedroom i have the original rpi 7 inch display. In the livingroom i hooked up a hdmi display. Both have the same glitch.

**Comment by pjmpessers** [comment]
![20210313_110757](https://user-images.githubusercontent.com/34476404/111026770-7dbd2380-83ec-11eb-967d-476d6f2f3c96.jpg)
![20210313_110639](https://user-images.githubusercontent.com/34476404/111026778-83b30480-83ec-11eb-9c47-961e277d94ee.jpg)

**Comment by pjmpessers** [comment]
![20210313_111227](https://user-images.githubusercontent.com/34476404/111026858-06d45a80-83ed-11eb-84aa-4057fc61b548.jpg)

**Comment by peted-davis** [comment]
Thanks for sharing the pictures. This is actually expected behaviour. If the hours or mins is less than 10, then they are not displayed with a leading zero. This is what it looks like on my display at the moment:

![Capture](https://user-images.githubusercontent.com/10545710/111027359-b27aac00-83e7-11eb-86f2-7e16531c2e24.PNG)

I understand why your display looks odd though, because on your display the hours and minutes are separated by a colon, which makes it look like a time. Are you running the latest version of the code (v4.0.4) as I actually removed the colon a number of versions back. The changes are made in the `wfpiconsole.kv` file. You may be overwriting this with the custom changes you are making to the display text sizes.

**Comment by pjmpessers** [comment]
You are right. I made a adjustment. Didn't know that it would also change in days. I now understand your intention with this. In that case, thanks. There is no need for adjustment and we can close this comment.

Thanks again.
