### ISSUE TITLE
Unable to Complete the CheckWX API Call

### ISSUE THREAD

**Issue by eoghanbacon** [peted-davis/WeatherFlow_PiConsole#36]
Hello,

I installed the software on a Raspberry PI 4.  The installation went fine by when I try to start the wfpiconsole, I get an error "unable to complete the checkwx API Call. 

I ran an update/upgrade on the OS and I still see the same error.  Anything I can do to trouble shoot the issue?

Thanks

**Comment by peted-davis** [comment]
I assume this is happening right after you enter your CheckWX API key for the first time? It generally happens because the API call to CheckWX using the key you entered is failing, most likely because there is an error in the key. Can you make sure you are copying the key correct? If it still doesn't work, can you open a terminal on the Rpi4 and copy this command:

`curl "https://api.checkwx.com/metar/KJFK" -H "X-API-Key: xxxx"`

Replace `xxxx` with your API key (make sure you don't delete the final `"`) and run the command. Let me know what output you see.
